---
# handlers file for nginx-role
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enable: yes

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
